```js
(() => {
  let x, y;
  try {
   throw new Error();
  } catch (x) {
   (x = 1), (y = 2);
   console.log(x); //1
  }
  console.log(x); //undefined 这里错了,我的答案是1
  console.log(y); //2
 })();
 
```

catch块接收参数x,当我们传递参数时,这里的x不是全局中的x了

他是参数x,是catch作用域中的局部变量	

所以下面的赋值是赋值给局部变量x

对全局中的x没有影响

